# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fd9a3fe3fcebb543a3e16cb6f10d158"
name = "my-test-app"
handle = "my-test-app-1224"
application_url = "https://pmc-challenge-fridge-nikon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-42fef51d.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pmc-challenge-fridge-nikon.trycloudflare.com/auth/callback",
  "https://pmc-challenge-fridge-nikon.trycloudflare.com/auth/shopify/callback",
  "https://pmc-challenge-fridge-nikon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
